# action.yml
name: "krew-release-bot"
description: "automatically opens PR for upstream krew-index repo when you publish new release of your awesome plugin"
runs:
  using: "docker"
  image: "docker://ghcr.io/rajatjindal/krew-release-bot:v0.0.50"
inputs:
  workdir:
    description: "Working directory, defaults to env.GITHUB_WORKSPACE"
  krew_template_file:
    description: "the path to template file relative to $workdir. e.g. templates/misc/plugin-name.yaml. defaults to .krew.yaml"
  krew_plugin_release_tag:
    description: "The tag to use as version for krew plugin release. e.g. 'v5.0.0'. Defaults to parsing GITHUB_REF"
