package actions

import (
	"os"

	"github.com/google/go-github/github"
)

//LocalAction for local action
type LocalAction struct{}

//GetActionData returns data to run on local laptop
func (l LocalAction) GetActionData(event *github.ReleaseEvent) (ActionData, error) {
	releaseInfo, err := getReleaseInfo(l.getPayload())
	if err != nil {
		return ActionData{}, err
	}

	return ActionData{
		Workspace:   "",
		Actor:       "rajatjindal",
		Repo:        "krew-plugin-release",
		RepoOwner:   "rajatjindal",
		ReleaseInfo: releaseInfo,
		Inputs: Inputs{
			PluginName:                "modify-secret",
			TokenUserHandle:           "rajatjindal",
			Token:                     os.Getenv("KREW_PLUGIN_RELEASE_TOKEN"),
			TokenUserEmail:            "rajatjindal83@gmail.com",
			TokenUserName:             "Rajat Jindal",
			UpstreamKrewIndexOwner:    "rajatjin",
			UpstreamKrewIndexRepoName: "krew-index",
		},
		Derived: Derived{
			UpstreamCloneURL: getRepoURL("rajatjin", "krew-index"),
			LocalCloneURL:    getRepoURL("rajatjindal", "krew-index"),
		},
	}, nil
}

func (l LocalAction) getPayload() []byte {
	return []byte(`{
		"action": "published",
		"release": {
			"assets": [
			{
				"browser_download_url": "https://github.com/rajatjindal/krew-plugin-release/releases/download/v0.0.6/darwin-amd64-v0.0.6.tar.gz",
				"content_type": "application/x-gzip",
				"created_at": "2019-09-30T10:51:23Z",
				"download_count": 0,
				"id": 15204574,
				"label": null,
				"name": "darwin-amd64-v0.0.6.tar.gz",
				"node_id": "MDEyOlJlbGVhc2VBc3NldDE1MjA0NTc0",
				"size": 9150835,
				"state": "uploaded",
				"updated_at": "2019-09-30T10:51:43Z",
				"uploader": {
				"avatar_url": "https://avatars2.githubusercontent.com/u/612092?v=4",
				"events_url": "https://api.github.com/users/rajatjindal/events{/privacy}",
				"followers_url": "https://api.github.com/users/rajatjindal/followers",
				"following_url": "https://api.github.com/users/rajatjindal/following{/other_user}",
				"gists_url": "https://api.github.com/users/rajatjindal/gists{/gist_id}",
				"gravatar_id": "",
				"html_url": "https://github.com/rajatjindal",
				"id": 612092,
				"login": "rajatjindal",
				"node_id": "MDQ6VXNlcjYxMjA5Mg==",
				"organizations_url": "https://api.github.com/users/rajatjindal/orgs",
				"received_events_url": "https://api.github.com/users/rajatjindal/received_events",
				"repos_url": "https://api.github.com/users/rajatjindal/repos",
				"site_admin": false,
				"starred_url": "https://api.github.com/users/rajatjindal/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/rajatjindal/subscriptions",
				"type": "User",
				"url": "https://api.github.com/users/rajatjindal"
				},
				"url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/releases/assets/15204574"
			},
			{
				"browser_download_url": "https://github.com/rajatjindal/krew-plugin-release/releases/download/v0.0.6/linux-amd64-v0.0.6.tar.gz",
				"content_type": "application/x-gzip",
				"created_at": "2019-09-30T10:50:34Z",
				"download_count": 0,
				"id": 15204570,
				"label": null,
				"name": "linux-amd64-v0.0.6.tar.gz",
				"node_id": "MDEyOlJlbGVhc2VBc3NldDE1MjA0NTcw",
				"size": 8657197,
				"state": "uploaded",
				"updated_at": "2019-09-30T10:51:02Z",
				"uploader": {
				"avatar_url": "https://avatars2.githubusercontent.com/u/612092?v=4",
				"events_url": "https://api.github.com/users/rajatjindal/events{/privacy}",
				"followers_url": "https://api.github.com/users/rajatjindal/followers",
				"following_url": "https://api.github.com/users/rajatjindal/following{/other_user}",
				"gists_url": "https://api.github.com/users/rajatjindal/gists{/gist_id}",
				"gravatar_id": "",
				"html_url": "https://github.com/rajatjindal",
				"id": 612092,
				"login": "rajatjindal",
				"node_id": "MDQ6VXNlcjYxMjA5Mg==",
				"organizations_url": "https://api.github.com/users/rajatjindal/orgs",
				"received_events_url": "https://api.github.com/users/rajatjindal/received_events",
				"repos_url": "https://api.github.com/users/rajatjindal/repos",
				"site_admin": false,
				"starred_url": "https://api.github.com/users/rajatjindal/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/rajatjindal/subscriptions",
				"type": "User",
				"url": "https://api.github.com/users/rajatjindal"
				},
				"url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/releases/assets/15204570"
			},
			{
				"browser_download_url": "https://github.com/rajatjindal/krew-plugin-release/releases/download/v0.0.6/sha256-darwin-amd64-v0.0.6",
				"content_type": "application/octet-stream",
				"created_at": "2019-09-30T10:51:23Z",
				"download_count": 0,
				"id": 15204575,
				"label": null,
				"name": "sha256-darwin-amd64-v0.0.6",
				"node_id": "MDEyOlJlbGVhc2VBc3NldDE1MjA0NTc1",
				"size": 65,
				"state": "uploaded",
				"updated_at": "2019-09-30T10:51:44Z",
				"uploader": {
				"avatar_url": "https://avatars2.githubusercontent.com/u/612092?v=4",
				"events_url": "https://api.github.com/users/rajatjindal/events{/privacy}",
				"followers_url": "https://api.github.com/users/rajatjindal/followers",
				"following_url": "https://api.github.com/users/rajatjindal/following{/other_user}",
				"gists_url": "https://api.github.com/users/rajatjindal/gists{/gist_id}",
				"gravatar_id": "",
				"html_url": "https://github.com/rajatjindal",
				"id": 612092,
				"login": "rajatjindal",
				"node_id": "MDQ6VXNlcjYxMjA5Mg==",
				"organizations_url": "https://api.github.com/users/rajatjindal/orgs",
				"received_events_url": "https://api.github.com/users/rajatjindal/received_events",
				"repos_url": "https://api.github.com/users/rajatjindal/repos",
				"site_admin": false,
				"starred_url": "https://api.github.com/users/rajatjindal/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/rajatjindal/subscriptions",
				"type": "User",
				"url": "https://api.github.com/users/rajatjindal"
				},
				"url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/releases/assets/15204575"
			},
			{
				"browser_download_url": "https://github.com/rajatjindal/krew-plugin-release/releases/download/v0.0.6/sha256-linux-amd64-v0.0.6",
				"content_type": "application/octet-stream",
				"created_at": "2019-09-30T10:50:35Z",
				"download_count": 0,
				"id": 15204571,
				"label": null,
				"name": "sha256-linux-amd64-v0.0.6",
				"node_id": "MDEyOlJlbGVhc2VBc3NldDE1MjA0NTcx",
				"size": 65,
				"state": "uploaded",
				"updated_at": "2019-09-30T10:51:02Z",
				"uploader": {
				"avatar_url": "https://avatars2.githubusercontent.com/u/612092?v=4",
				"events_url": "https://api.github.com/users/rajatjindal/events{/privacy}",
				"followers_url": "https://api.github.com/users/rajatjindal/followers",
				"following_url": "https://api.github.com/users/rajatjindal/following{/other_user}",
				"gists_url": "https://api.github.com/users/rajatjindal/gists{/gist_id}",
				"gravatar_id": "",
				"html_url": "https://github.com/rajatjindal",
				"id": 612092,
				"login": "rajatjindal",
				"node_id": "MDQ6VXNlcjYxMjA5Mg==",
				"organizations_url": "https://api.github.com/users/rajatjindal/orgs",
				"received_events_url": "https://api.github.com/users/rajatjindal/received_events",
				"repos_url": "https://api.github.com/users/rajatjindal/repos",
				"site_admin": false,
				"starred_url": "https://api.github.com/users/rajatjindal/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/rajatjindal/subscriptions",
				"type": "User",
				"url": "https://api.github.com/users/rajatjindal"
				},
				"url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/releases/assets/15204571"
			}
			],
			"assets_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/releases/20348112/assets",
			"author": {
			"avatar_url": "https://avatars2.githubusercontent.com/u/612092?v=4",
			"events_url": "https://api.github.com/users/rajatjindal/events{/privacy}",
			"followers_url": "https://api.github.com/users/rajatjindal/followers",
			"following_url": "https://api.github.com/users/rajatjindal/following{/other_user}",
			"gists_url": "https://api.github.com/users/rajatjindal/gists{/gist_id}",
			"gravatar_id": "",
			"html_url": "https://github.com/rajatjindal",
			"id": 612092,
			"login": "rajatjindal",
			"node_id": "MDQ6VXNlcjYxMjA5Mg==",
			"organizations_url": "https://api.github.com/users/rajatjindal/orgs",
			"received_events_url": "https://api.github.com/users/rajatjindal/received_events",
			"repos_url": "https://api.github.com/users/rajatjindal/repos",
			"site_admin": false,
			"starred_url": "https://api.github.com/users/rajatjindal/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/rajatjindal/subscriptions",
			"type": "User",
			"url": "https://api.github.com/users/rajatjindal"
			},
			"body": "v0.0.6",
			"created_at": "2019-09-29T15:14:53Z",
			"draft": false,
			"html_url": "https://github.com/rajatjindal/krew-plugin-release/releases/tag/v0.0.6",
			"id": 20348112,
			"name": "release v0.0.6",
			"node_id": "MDc6UmVsZWFzZTIwMzQ4MTEy",
			"prerelease": false,
			"published_at": "2019-09-30T10:51:48Z",
			"tag_name": "v0.0.6",
			"tarball_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/tarball/v0.0.6",
			"target_commitish": "master",
			"upload_url": "https://uploads.github.com/repos/rajatjindal/krew-plugin-release/releases/20348112/assets{?name,label}",
			"url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/releases/20348112",
			"zipball_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/zipball/v0.0.6"
		},
		"repository": {
			"archive_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/{archive_format}{/ref}",
			"archived": false,
			"assignees_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/assignees{/user}",
			"blobs_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/git/blobs{/sha}",
			"branches_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/branches{/branch}",
			"clone_url": "https://github.com/rajatjindal/krew-plugin-release.git",
			"collaborators_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/collaborators{/collaborator}",
			"comments_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/comments{/number}",
			"commits_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/commits{/sha}",
			"compare_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/compare/{base}...{head}",
			"contents_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/contents/{+path}",
			"contributors_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/contributors",
			"created_at": "2019-09-29T10:03:17Z",
			"default_branch": "master",
			"deployments_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/deployments",
			"description": null,
			"disabled": false,
			"downloads_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/downloads",
			"events_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/events",
			"fork": false,
			"forks": 0,
			"forks_count": 0,
			"forks_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/forks",
			"full_name": "rajatjindal/krew-plugin-release",
			"git_commits_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/git/commits{/sha}",
			"git_refs_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/git/refs{/sha}",
			"git_tags_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/git/tags{/sha}",
			"git_url": "git://github.com/rajatjindal/krew-plugin-release.git",
			"has_downloads": true,
			"has_issues": true,
			"has_pages": false,
			"has_projects": true,
			"has_wiki": true,
			"homepage": null,
			"hooks_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/hooks",
			"html_url": "https://github.com/rajatjindal/krew-plugin-release",
			"id": 211642796,
			"issue_comment_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/issues/comments{/number}",
			"issue_events_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/issues/events{/number}",
			"issues_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/issues{/number}",
			"keys_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/keys{/key_id}",
			"labels_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/labels{/name}",
			"language": "Go",
			"languages_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/languages",
			"license": null,
			"merges_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/merges",
			"milestones_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/milestones{/number}",
			"mirror_url": null,
			"name": "krew-plugin-release",
			"node_id": "MDEwOlJlcG9zaXRvcnkyMTE2NDI3OTY=",
			"notifications_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/notifications{?since,all,participating}",
			"open_issues": 0,
			"open_issues_count": 0,
			"owner": {
			"avatar_url": "https://avatars2.githubusercontent.com/u/612092?v=4",
			"events_url": "https://api.github.com/users/rajatjindal/events{/privacy}",
			"followers_url": "https://api.github.com/users/rajatjindal/followers",
			"following_url": "https://api.github.com/users/rajatjindal/following{/other_user}",
			"gists_url": "https://api.github.com/users/rajatjindal/gists{/gist_id}",
			"gravatar_id": "",
			"html_url": "https://github.com/rajatjindal",
			"id": 612092,
			"login": "rajatjindal",
			"node_id": "MDQ6VXNlcjYxMjA5Mg==",
			"organizations_url": "https://api.github.com/users/rajatjindal/orgs",
			"received_events_url": "https://api.github.com/users/rajatjindal/received_events",
			"repos_url": "https://api.github.com/users/rajatjindal/repos",
			"site_admin": false,
			"starred_url": "https://api.github.com/users/rajatjindal/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/rajatjindal/subscriptions",
			"type": "User",
			"url": "https://api.github.com/users/rajatjindal"
			},
			"private": true,
			"pulls_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/pulls{/number}",
			"pushed_at": "2019-09-30T10:51:48Z",
			"releases_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/releases{/id}",
			"size": 1238,
			"ssh_url": "git@github.com:rajatjindal/krew-plugin-release.git",
			"stargazers_count": 0,
			"stargazers_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/stargazers",
			"statuses_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/statuses/{sha}",
			"subscribers_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/subscribers",
			"subscription_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/subscription",
			"svn_url": "https://github.com/rajatjindal/krew-plugin-release",
			"tags_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/tags",
			"teams_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/teams",
			"trees_url": "https://api.github.com/repos/rajatjindal/krew-plugin-release/git/trees{/sha}",
			"updated_at": "2019-09-29T15:15:04Z",
			"url": "https://api.github.com/repos/rajatjindal/krew-plugin-release",
			"watchers": 0,
			"watchers_count": 0
		},
		"sender": {
			"avatar_url": "https://avatars2.githubusercontent.com/u/612092?v=4",
			"events_url": "https://api.github.com/users/rajatjindal/events{/privacy}",
			"followers_url": "https://api.github.com/users/rajatjindal/followers",
			"following_url": "https://api.github.com/users/rajatjindal/following{/other_user}",
			"gists_url": "https://api.github.com/users/rajatjindal/gists{/gist_id}",
			"gravatar_id": "",
			"html_url": "https://github.com/rajatjindal",
			"id": 612092,
			"login": "rajatjindal",
			"node_id": "MDQ6VXNlcjYxMjA5Mg==",
			"organizations_url": "https://api.github.com/users/rajatjindal/orgs",
			"received_events_url": "https://api.github.com/users/rajatjindal/received_events",
			"repos_url": "https://api.github.com/users/rajatjindal/repos",
			"site_admin": false,
			"starred_url": "https://api.github.com/users/rajatjindal/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/rajatjindal/subscriptions",
			"type": "User",
			"url": "https://api.github.com/users/rajatjindal"
		}
		}`)
}
